apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-okteto-ingress
  labels:
    name: node-okteto-ingress
spec:
  rules:
  - host: localdev.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: node-okteto-svc
            port: 
              number: 3000
